-module(email_address_tests).
-include_lib("eunit/include/eunit.hrl").

email_validation_test_() ->
       [?_assert(email_address:is_valid("\"Abc\@def\"@example.com")),
	?_assert(email_address:is_valid("\"Fred Bloggs\"@example.com")),
	?_assert(email_address:is_valid("\"Joe\\Blow\"@example.com")),
	?_assert(email_address:is_valid("\"Abc@def\"@example.com")),
	?_assert(email_address:is_valid("customer/department=shipping@example.com")),
	?_assert(email_address:is_valid("$A12345@example.com")),
	?_assert(email_address:is_valid("!def!xyz%abc@example.com")),
	?_assert(email_address:is_valid("_somename@example.com")),
	?_assert(email_address:is_valid("normal@example.com")),
	?_assert(email_address:is_valid("firstname.lastname@example.com")),
	?_assert(email_address:is_valid("email@subdomain.example.com")),
	?_assert(email_address:is_valid("firstname+lastname@example.com")),
	?_assert(email_address:is_valid("email@123.123.123.123")),
	?_assert(email_address:is_valid("email@[123.123.123.123]")),
	?_assert(email_address:is_valid("\"email\"@example.com")),
	?_assert(email_address:is_valid("1234567890@example.com")),
	?_assert(email_address:is_valid("email@example-one.com")),
	?_assert(email_address:is_valid("_______@example.com")),
	?_assert(email_address:is_valid("email@example.name")),
	?_assert(email_address:is_valid("email@example.museum")),
	?_assert(email_address:is_valid("email@example.co.jp")),
	?_assert(email_address:is_valid("firstname-lastname@example.com")),
	?_assert(email_address:is_valid("much.\"more\ unusual\"@example.com")),
	?_assert(email_address:is_valid("very.unusual.\"@\".unusual.com@example.com")),
	?_assert(email_address:is_valid("very.\"(),:;<>[]\".VERY.\"very@\\ very\".unusual@strange.example.com")),

	?_assertNot(email_address:is_valid("plainaddress")),
	?_assertNot(email_address:is_valid("#@%^%#$@#$@#.com")),
	?_assertNot(email_address:is_valid("@example.com")),
	?_assertNot(email_address:is_valid("Joe Smith <email@example.com>")),
	?_assertNot(email_address:is_valid("email.example.com")),
	?_assertNot(email_address:is_valid("email@example@example.com")),
	?_assertNot(email_address:is_valid(".email@example.com")),
	?_assertNot(email_address:is_valid("email.@example.com")),
	?_assertNot(email_address:is_valid("email..email@example.com")),
	?_assertNot(email_address:is_valid("あいうえお@example.com")),
	?_assertNot(email_address:is_valid("email@example.com (Joe Smith)")),
	?_assertNot(email_address:is_valid("email@example")),
	?_assertNot(email_address:is_valid("email@-example.com")),
	?_assertNot(email_address:is_valid("email@example.web")),
	?_assertNot(email_address:is_valid("email@111.222.333.44444")),
	?_assertNot(email_address:is_valid("email@example..com")),
	?_assertNot(email_address:is_valid("Abc..123@example.com")),
	?_assertNot(email_address:is_valid("\"(),:;<>[\]@example.com")),
	?_assertNot(email_address:is_valid("just\"not\"right@example.com")),
	?_assertNot(email_address:is_valid("this is\"really\"not\allowed@example.com"))
       ].
